os: Visual Studio 2015
platform: x86

environment:
 BOOST_ROOT: C:\Libraries\boost_1_63_0
 BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib32-msvc-14.0
 RAPIDJSON_URL: https://github.com/Tencent/rapidjson.git
 GETTEXTURL: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.14/gettext0.19.8.1-iconv1.14-shared-32.zip
 TMDB_KEY:
    secure: WoegXMAfCW6Zfwq+5xBZXpy0KL5UtTPg1QIDF/EuxuT4/MPhHyUrA7z9MQXwiXgn
 GTEST_URL: https://github.com/google/googletest.git

version: 1.0.{build}

#only_commits:
#  message: /build/

before_build:
 - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
 - cmd: mkdir sdk
 - cmd: mkdir build
 - cmd: cd sdk
 - cmd: SET RJPATH=%CD%\rapidjson
 - cmd: git clone %RAPIDJSON_URL%
 - cmd: SET include=%RJPATH%\include;%include%
 - cmd: git clone %GTEST_URL%
 - cmd: SET GTEST_ROOT=%CD%\gtest
 - cmd: SET include=%GTEST_ROOT%\include;%include%
 - cmd: SET lib=%GTEST_ROOT%\lib;%lib%
 - cmd: cd googletest
 - cmd: cmake -G "NMake Makefiles" -Dgtest_force_shared_crt=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%GTEST_ROOT% .
 - cmd: nmake install
 - cmd: cd ..
 - cmd: mkdir ttscmd
 - cmd: set lib=%BOOST_LIBRARYDIR%;%lib%
# - ps: $wc = New-Object System.Net.WebClient
# - ps: $wc.DownloadFile("$env:GETTEXTURL", "$pwd\gettext.zip")
# - ps: Expand-Archive gettext.zip -DestinationPath $pwd\gettext
 - cmd: PATH=%CD%\gettext\bin;%PATH%
 - cmd: cd ..

build_script:
 - cmd: cd build
 - cmd: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\ttscmd -DTMDB_API_KEY=%TMDB_KEY% -DTMDB_TEST=ON ..
 - cmd: nmake
 - cmd: cd ..
 
test_script:
 - cmd: cd build
 - cmd: ctest -V
 - cmd: cd ..
 
 

 


