image: gcc:latest

build:
    tags:
        - linux
    script:
        - mkdir -p b
        - cd b
        - cmake -DCMAKE_BUILD_TYPE=Release 
           -DTMDB_API_KEY=$TMDB_KEY 
           -BUILD_TEST=ON ..
        - make -j 4
        - ctest -V
