stages:
    - test
    - sonar


build-linux:
    tags:
        - linux
        - docker
        - x64
    image: ubuntu:24.04 
    stage: test   
    before_script:
        - export TZ=Europe/Dublin
        - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
        - apt -y update && apt -y install gcc g++ cmake make git ssh
        - apt -y install libboost1.83-all-dev libssl-dev rapidjson-dev libicu-dev libcurl4-openssl-dev libgtest-dev    
    script:
        - mkdir -p build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Release 
           -DTMDB_API_KEY=$TMDB_KEY 
           -DBUILD_TEST=ON 
           -DBUILD_STATIC=ON
           -DBUILD_SHARED=OFF
           ..
        - make
        - ctest -V

build-windows:
    tags:
        - windows
        - native
        - x64
    stage: test
    script: 
        - cmd /c build-windows.bat
        
sonar-linux:
    stage: sonar
    image: ubuntu:24.04
    tags:
        - linux
        - docker
        - x64
    allow_failure: true
    before_script:
        - export TZ=Europe/Dublin
        - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
        - apt -y update && apt -y install gcc g++ cmake make git ssh
        - apt -y install libboost1.83-all-dev libssl-dev rapidjson-dev libicu-dev libcurl4-openssl-dev libgtest-dev
        - apt -y install unzip curl wget
        - mkdir -p .sonar/bw-output
        - curl -sSLo build-wrapper-linux-x86.zip  $SONAR_HOST_URL/static/cpp/build-wrapper-linux-x86.zip
        - unzip -o build-wrapper-linux-x86.zip -d .sonar
        - curl -sSLo sonar-scanner.zip  https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip
        - export kkey=sonar-scanner-6.1.0.4477-linux-x64
        - unzip -o sonar-scanner.zip -d .sonar 
    script:
        - cmake -DCMAKE_BUILD_TYPE=Release
            -DTMDB_API_KEY=$TMDB_KEY -DBUILD_TEST=ON -DBUILD_STATIC=ON -DBUILD_SHARED=OFF .      
        - .sonar/build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir .sonar/bw-output make
        - .sonar/$kkey/bin/sonar-scanner -Dsonar.cfamily.build-wrapper-output=.sonar/bw-output
            -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.token="${SONAR_TOKEN}"
    cache:
      paths:
        - .sonar
        - .gcov



        
