

build:
    tags:
        - linux
        - docker
    image: ubuntu:18.04
    script:
        - mkdir -p b
        - cd b
        - cmake -DCMAKE_BUILD_TYPE=Release 
           -DTMDB_API_KEY=$TMDB_KEY 
           -DBUILD_TEST=ON 
           -DBUILD_STATIC=ON
           -DBUILD_SHARED=OFF
           ..
        - make -j 4
        - ctest -V
