build-nix:
    tags:
        - linux
        - docker
    image: ubuntu:18.04
    
    before_script:
        - apt -y update
        - apt -y install gcc
        - apt -y install cmake
        - apt -y install libboost1.65-all-dev
        - apt -y install libssl-dev
        - apt -y install rapidjson-dev
        - apt -y install libicu-dev
        - apt -y install libcurl4-openssl-dev
        - apt -y install libgtest-dev
        - c=$PWD
        - cd /usr/src/gtest
        - cmake CMakeLists.txt
        - make
        - cp *.a /usr/lib
        - cd $c
    
    script:
        - mkdir -p b
        - cd b
        - cmake -DCMAKE_BUILD_TYPE=Release 
           -DTMDB_API_KEY=$TMDB_KEY 
           -DBUILD_TEST=ON 
           -DBUILD_STATIC=ON
           -DBUILD_SHARED=OFF
           ..
        - make -j 4
        - ctest -V
        


build-win10:
    tags:
        - windows
        - win10

    before_script:
        - cmd /c "echo call vcvarsall.bat x64 > b.bat"
        - cmd /c "echo SET PATH=e:\sdk\shared\bin:%PATH% >> b.bat"
        - cmd /c "echo SET include=e:\sdk\shared\include:%include% >> b.bat"
        - cmd /c "echo SET lib=e:\sdk\shared\lib:%lib% >> b.bat"
        - cmd /c 'echo cmake -G "NMake Makefiles" -DTMDB_API_KEY=%TMDB_KEY% -DBUILD_TEST=ON . >> b.bat'
        - cmd /c "echo nmake >> b.bat"
        - cmd /c "echo ctest -V >> b.bat"

    script: 
        - cmd /c b.bat
        
