
language: cpp
dist: trusty
compiler:
 - gcc
os:
 - linux

matrix:
  include:
   - os: linux
     addons:
      apt:
       sources:
        - ubuntu-toolchain-r-test
       packages:
        - g++-7
     env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



env:
 global:
  - RAPID_JSON_URL=https://github.com/Tencent/rapidjson.git
  - GTEST_URL=https://github.com/google/googletest.git

branches:
 only:
  - master

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-all-dev

script:
 - cd $TRAVIS_BUILD_DIR
 - mkdir -p sdk
 - cd sdk
 - git clone $RAPID_JSON_URL
 - git clone $GTEST_URL
 - export SDK_DIR={$TRAVIS_BUILD_DIR}/sdk
 - cd googletest
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/sdk/gtest .
 - make
 - make install
 - cd ../..
 - export CPATH=${SDK_DIR}/gtest/include:${SDK_DIR}/rapidjson/include:$CPATH    
 - export LD_LIBRARY_PATH=$SDK_DIR/gtest/lib
 - mkdir -p build
 - cd build
 - cmake
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DTMDB_API_KEY=${TMDB_KEY} ..
 - ctest -V 



 