
language: cpp
dist: trusty
sudo: required
compiler:
 - gcc
os:
 - linux

matrix:
  include:
   - os: linux
     addons:
      apt:
       sources:
        - ubuntu-toolchain-r-test
       packages:
        - g++-7
     env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



env:
 global:
  - RAPID_JSON_URL=https://github.com/Tencent/rapidjson.git
  - GTEST_URL=https://github.com/google/googletest.git
  - BOOST_URL=https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2

branches:
 only:
  - master
  
cache:
 directories:
  ${HOME}/depend

before_install:
  - eval "${MATRIX_EVAL}"
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libboost-all-dev
  - cd ${HOME}
  - mkdir -p depend
  - cd depend
  - if [ ! -d rapidjson ]; then git clone $RAPID_JSON_URL; fi
  - if [ ! -d googletest ]; then git clone $GTEST_URL; fi
  - if [ ! -f boost_1_66_0.tar.bz2 ]; then wget $BOOST_URL; fi
  - if [ ! -d boost_1_66_0 ]; then tar -xjf boost*.tar.bz2; fi
  - cd boost_1_66_0
  - ./bootstrap.sh
  - ./b2 stage
  - sudo ./b2 install --prefix=/usr
  - cd ..
  - cd googletest
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
  - make
  - sudo make install
  - cd ..
  - cd rapidjson
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
  - make
  - sudo make install

script:
 - cd $TRAVIS_BUILD_DIR 
 - mkdir -p build
 - cd build
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DTMDB_API_KEY=${TMDB_KEY} -DTMDB_TEST=ON ..
 - make
 - ctest -V 



 