
language: cpp
dist: trusty
sudo: required
compiler:
 - gcc
os:
 - linux

matrix:
  include:
   - os: linux
     addons:
      apt:
       sources:
        - ubuntu-toolchain-r-test
       packages:
        - g++-7
     env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



env:
 global:
  - RAPID_JSON_URL=https://github.com/Tencent/rapidjson.git
  - GTEST_URL=https://github.com/google/googletest.git
  - BOOST_URL=https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
  - CMAKE_URL=https://cmake.org/files/v3.10/cmake-3.10.2.tar.gz

branches:
 only:
  - master
  
cache:
 directories:
  ${HOME}/depend

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get install -y curl
  - cd ${HOME}
  - mkdir -p depend
  - cd depend
  - if [ ! -f cmake-3.10.2.tar.gz ]; then wget $CMAKE_URL; fi
  - if [ ! -d cmake-3.10.2 ]; then tar -xzf cmake-3.10.2.tar.gz; fi
  - if [ ! -d rapidjson ]; then git clone $RAPID_JSON_URL; fi
  - if [ ! -d googletest ]; then git clone $GTEST_URL; fi
  - if [ ! -f boost_1_65_1.tar.gz ]; then curl -Ls -o boost_1_65_1.tar.gz $BOOST_URL; fi
  - if [ ! -d boost_1_65_1 ]; then tar -xzf boost_1_65_1.tar.gz; fi
  - cd cmake-3.10.2
  - ./configure --prefix=/usr
  - make > /dev/null
  - sudo make install > /dev/null
  - cd ..
  - cd boost_1_65_1
  - ./bootstrap.sh
  - ./b2 stage > /dev/null
  - sudo ./b2 install --prefix=/usr > /dev/null
  - cd ..
  - cd googletest
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
  - make > /dev/null
  - sudo make install > /dev/null
  - cd ..
  - cd rapidjson
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
  - make > /dev/null
  - sudo make install > /dev/null

script:
 - cd $TRAVIS_BUILD_DIR 
 - eval "${MATRIX_EVAL}"
 - mkdir -p build
 - cd build
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DTMDB_API_KEY=${TMDB_KEY} -DTMDB_TEST=ON ..
 - make
 - ctest -V 



 