
language: cpp
dist: trusty
sudo: required
compiler:
 - gcc
os:
 - linux

matrix:
  include:
   - os: linux
     addons:
      apt:
       sources:
        - ubuntu-toolchain-r-test
       packages:
        - g++-7
     env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



env:
 global:
  - RAPID_JSON_URL=https://github.com/Tencent/rapidjson.git
  - GTEST_URL=https://github.com/google/googletest.git

branches:
 only:
  - master

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-all-dev

script:
 - cd $TRAVIS_BUILD_DIR
 - mkdir -p sdk
 - cd sdk
 - git clone $RAPID_JSON_URL
 - git clone $GTEST_URL
 - cd googletest
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
 - make
 - sudo make install
 - cd ..
 - cd rapidjson
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
 - make
 - sudo make install
 - cd ../..
 - mkdir -p build
 - cd build
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DTMDB_API_KEY=${TMDB_KEY} -DTMDB_TEST=ON ..
 - ctest -V 



 